version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "content/specs"
    schedule:
      interval: "daily"
