baseURL = "https://scientific-python.org"
languageCode = "en-us"
title = "Scientific Python Ecosystem"
subtitle = "Planning for the next decade"
theme = "mainroad"
uglyurls = true
relativeURLs=true

[Params]
  mainSections = ["_index"]
  post_meta = ["author", "date", "spec_fields"]
  customCSS = ["css/custom.css"]

[Params.sidebar]
  home = "right"
  single = "right"
  list = "right"
  not_for = ["specs", "summits"]
  widgets = ["search", "pinned", "sidemenu", "recent", "taglist", "social"]

[Params.logo]
  title = "The Scientific Python Ecosystem" # Logo title, otherwise will use site title
  subtitle = "Planning for the next decade" # Logo subtitle
  image = "img/ecosystem.svg" # Logo image. Path relative to "static"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/index.html"
    weight = 10
  [[menu.main]]
    name = "ABOUT"
    identifier = "about"
    url = "/about.html"
    weight = 20
  [[menu.main]]
    name = "POSTS"
    identifier = "posts"
    url = "/posts.html"
    weight = 30
  [[menu.main]]
    name = "SPECS"
    identifier = "specs"
    url = "/specs.html"
    weight = 40
  [[menu.main]]
    name = "SUMMITS"
    identifier = "summits"
    url = "/summits.html"
    weight = 50

[Params.widgets.social]
  github = "scientific-python"

[[Params.widgets.social.custom]]
  title = "Youtube"
  url = "https://www.youtube.com/channel/UC2wKi87Wmy9C1OQMyD9fGxA"
