version: 2.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cibuilds/hugo:latest

    steps:
      - checkout

      - run:
          name: Install hugo theme
          command: git submodule update --init --recursive

      - run:
          # TODO: include --buildDrafts?
          name: Build site
          command: |
            sed -i '1s/^/uglyurls: true\n/' config.yaml
            sed -i 's/\(url: \/.\+\)\//\1.html/' config.yaml
            sed -i 's/url: \/$/url: \/index.html/' config.yaml
            sed -i 's/\(link: \/.\+\)\//\1.html/' config.yaml
            sed -i 's/\(buttonlink: \/.\+\)\//\1.html/' config.yaml
            sed -i 's/link: \/$/link: \/index.html/' config.yaml
            hugo --buildDrafts

      - store_artifacts:
          path: public/
