version: 2.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cibuilds/hugo:latest

    steps:
      - checkout

      - run:
          name: Install hugo theme
          command: git submodule update --init

      - run:
          # TODO: include --buildDrafts?
          name: Build site
          command: hugo

      - store_artifacts:
          path: public/
