name: Create New Discourse Category
description: Request a new category for our discourse forum (https://discuss.scientific-python.org/)
labels: ["discourse"]

body:
  - type: markdown
    attributes:
      value: Thank you for your interest in our discussion forum.
  - type: markdown
    attributes:
      value: Before continuing, you may want to review the difference between [categories and tags](https://blog.discourse.org/2017/10/its-time-we-talked-about-tags/).
  - type: textarea
    attributes:
      label: Describe your issue.
    validations:
      required: true
