name: Feature Request
description: Please describe the new feature.
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: If you have a general question about Scientific Python, please use our discussion forum https://discuss.scientific-python.org.
  - type: markdown
    attributes:
      value: Provide a general summary of the new feature in the Title above.
  - type: textarea
    attributes:
      label: Please describe the new feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Add any other context about the new feature here, screenshots, etc.
    validations:
      required: false
